Repository GEOS-ESM/GFDL_atmos_cubed_sphere, pull requests merged in 2019-10, with the labels that each got.

#6 Fixes #1. Rename GFDL_fms to fms
  CMakeLists.txt
Labels: 0 diff structural

#9 Merge master into MAPL 2.0 branch
  CMakeLists.txt
Labels: 0 diff structural

#11 Fixes #10 - Rename GFDL_fms to fms in mapz driver
  model/mapz-driver/CMakeLists.txt
Labels: 0 diff structural

#14 Convert _VERIFY and _RETURN to VERIFY_ and RETURN_
  geos_utils/rs_scaleMod.F90
Labels: 0 diff trivial

#15 Merge geos/develop into geos/MAPL-2.0
  CMakeLists.txt
  model/mapz-driver/CMakeLists.txt
  model/mapz-driver/input/input_array_extents.f90
  model/mapz-driver/input/input_arrays.f90
  model/mapz-driver/input/input_domain_layout.f90
  model/mapz-driver/input/input_flagstruct.f90
  model/mapz-driver/input/input_gridstruct.f90
  model/mapz-driver/input/input_scalars.f90
  model/mapz-driver/main.F90
  model/mapz-driver/output/output.f90
  model/mapz-driver/stubs/external_ic_stub.F90
  model/mapz-driver/stubs/fv_grid_utils_stub.f90
Labels: 0 diff structural

#16 Update mapz-driver cmakelists.txt for GCC
  model/mapz-driver/CMakeLists.txt
Labels: 0 diff

#17 Pull GCC fix from develop to MAPL-2.0
  model/mapz-driver/CMakeLists.txt
Labels: 0 diff, 0 diff trivial
